config/routes.rb
Rails.application.routes.draw do
  resources :file, only: [:index, :create] do
    member do
      get :download
    end
  end

  root 'file#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/file_controller.rb
require 'zip'

class FileController < ApplicationController
  def index
    @password = ENV['PASSWORD'].present? ? Date.today.strftime(ENV['PASSWORD']) : ""
    @zip_id = SecureRandom.hex(16)
    gon.zip_id = @zip_id
  end

  def create
    tmp_path = File.join("/tmp/", params[:zip_id])
    FileUtils.mkdir_p(tmp_path)
    file_path = File.join(tmp_path, params[:file].original_filename)
    File.open(file_path, 'wb') do |f|
      f.write(params[:file].read)
    end
    render json: {status: "success"}
  end

  def download
    zip_id = params[:id]
    unless File.exist?(File.join("/tmp/", zip_id))
      redirect_to :file_index
      return
    end
    encrypter = params[:password].present? ? Zip::TraditionalEncrypter.new(params[:password]) : nil
    io = StringIO.new('')
    io.set_encoding(Encoding::CP932)
    buffer = Zip::OutputStream.write_buffer(io, encrypter) do |zos|
      Dir.glob(File.join("/tmp/", zip_id, "*")).each do |file_path|
        zos.put_next_entry File.basename(file_path).unicode_normalize.encode("CP932", invalid: :replace, undef: :replace, replace: "■")
        open(file_path, "rb") do |f|
          zos.write f.read
        end
      end
    end
    send_data buffer.string, filename: "#{zip_id}.zip", type: 'application/zip', disposition: 'attachment'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_helper.rb
module FileHelper
end

app/views/file/index.html.erb
<%= form_tag(file_index_path, class: 'dropzone', id: 'upload-dropzone') do %>
  <div class="fallback">
    <%= hidden_field_tag :abc, 123 %>
  </div>
<% end %>

<div class="download">
  <%= form_tag(download_file_path(@zip_id), data: { turbolinks: false }, method: :get) do %>
    <p>
      password: <%= text_field_tag :password, @password %>
    </p>
    <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
      <i class="fa fa-download fa-5x"></i>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zip4win</title>
  <%= Gon::Base.render_data %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>